version: '3.4'

networks:
  k6:
    attachable: true
  grafana:
  telegraf:

services:
  telegraf:
    hostname: "{{.Node.Hostname}}"
    image: telegraf:latest
    networks:
      - telegraf
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    configs:
      - source: telegraf.conf
        target: /etc/telegraf/telegraf.conf
    deploy:
      mode: global

  influxdb:
    image: influxdb:1.8
    networks:
      - k6
      - grafana
      - telegraf
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    volumes:
      - influxdb_volume:/var/lib/influxdb
    deploy:
      placement:
        constraints:
          - node.labels.influxdb == true

  grafana:
    image: grafana/grafana:latest
    networks:
      - grafana
    ports:
      - "3000:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_BASIC_ENABLED=false
    volumes:
      - ./dashboards:/var/lib/grafana/dashboards
      - ./grafana-dashboard.yaml:/etc/grafana/provisioning/dashboards/dashboard.yaml
      - ./grafana-datasource.yaml:/etc/grafana/provisioning/datasources/datasource.yaml
      - grafana_volume:/var/lib/grafana
      - ./grafana.ini:/etc/grafana/grafana.ini
    deploy:
      placement:
        constraints:
          - node.labels.grafana == true

configs:
  telegraf.conf:
    file: ./telegraf/telegraf.conf

volumes:
  influxdb_volume:
  grafana_volume:
