version: '3.4'

networks:
  MONITORING_k6:
    external: true

services:
  k6:
    image: loadimpact/k6:latest
    networks:
      - MONITORING_k6
    ports:
      - "6565:6565"
    environment:
      - K6_OUT=influxdb=http://influxdb:8086/k6
    volumes:
      - ./scripts:/scripts
    entrypoint: ['k6', 'run', '/scripts/k6_test.js']
    deploy:
      restart_policy:
        condition: none
#      指定哪個node來跑
#      placement:
#        constraints:
#          - node.role == manager
